spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  application:
    name: "WHUAssist"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whuassistlocal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: huawei+123

#private static final String URL = "jdbc:mysql://150.158.4.187:3306/whuassist";//数据库连接字符串
#private static final String NAME = "remoteUser";//登录名
#private static final String PASSWORD = "huawei+123";//密码
#
mybatis-plus:
  type-enums-package: org.rainark.whuassist.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

server:
  port: 8081

#配置路径

file:
  uploadQcFolder: C://Users//JeremyHua//wechatWHU//
  uploadUserFolder: C://Users//JeremyHua//wechatWHU//
